image: "debian:stretch"

build:
  stage: build
  before_script:
    - apt-get update -y
    - apt-get install -y make python3-pip sfst hfst
    - pip3 install hfst
  script:
    - make
  artifacts:
    paths:
    - malayalam.a

test:
  stage: test
  before_script:
    - apt-get update -y
    - apt-get install -y make python3-pip sfst hfst
    - pip3 install hfst
  script:
    - make test
